networks:
  CoGame_Phone:
    driver: bridge

services:
  basqiz:
    build:
      context: ./app4
      dockerfile: ../build/Dockerfile
    restart: always
    networks:
      - CoGame_Phone
    working_dir: /usr/src/app
    volumes:
      - ./app4:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "28331:3000"
    command: sh -c "npm install && node server.js"

  tombecreuse:
    build:
      context: ./TombeCreuse
      dockerfile: ../build/Dockerfile
    restart: always
    networks:
      - CoGame_Phone
    working_dir: /usr/src/app
    volumes:
      - ./TombeCreuse:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "28332:3000"
    command: sh -c "npm install && node server.js"
