networks:
  CoGame_Phone:
    driver: bridge

services:
  basqiz:
    build:
      context: build
      dockerfile: Dockerfile
    restart: always
    networks:
      - CoGame_Phone
    working_dir: /usr/src/app
    volumes:
      - ./app4:/usr/src/app
    ports:
      - "28331:3000"
    command: node server.js

  tombecreuse:
    build:
      context: build
      dockerfile: Dockerfile
    restart: always
    networks:
      - CoGame_Phone
    working_dir: /usr/src/app
    volumes:
      - ./TombeCreuse:/usr/src/app
    ports:
      - "28332:3000"
    command: node server.js
